### ISSUE TITLE
Set up theming

### ISSUE THREAD

**Issue by MachkrXXIV** [MachkrXXIV/HogSpot#1]
As a developer, I want to be able to quickly access theming resources so that I can quickly apply styling to components and so that our app remains consistent

For this story, we want to set variables and styling so our app is consistent and we don't have to worry about this kind of thing. We would want:

**Colors**
- background-dark
- foreground-dark
- brand-color
- button-primary
- button -secondary
- text-primary
- text-secondary
- text-tertiary
- gold
- silver
- bronze

**font**
- regular
- bold

**font sizing**
- heading
- subheading
- paragraph

**border radius**

**padding and margin**

**icons**
- explore
- add spot
- error
- saved spots/ your spots / profile
- full star / half-star / empty star
- x button

**Comment by jordicastro** [comment]
ill take this one!

**Comment by jordicastro** [comment]
> As a developer, I want to be able to quickly access theming resources so that I can quickly apply styling to components and so that our app remains consistent
> 
> For this story, we want to set variables and styling so our app is consistent and we don't have to worry about this kind of thing. We would want:
> 
> **Colors**
> 
> * background-dark
> * foreground-dark
> * brand-color
> * button-primary
> * button -secondary
> * text-primary
> * text-secondary
> * text-tertiary
> * gold
> * silver
> * bronze
> 
> **font**
> 
> * regular
> * bold
> 
> **font sizing**
> 
> * heading
> * subheading
> * paragraph
> 
> **border radius**
> 
> **padding and margin**
> 
> **icons**
> 
> * explore
> * add spot
> * error
> * saved spots/ your spots / profile
> * full star / half-star / empty star
> * x button

adding something
