### ISSUE TITLE
UI: Create Login/Sign-up Activity

### ISSUE THREAD

**Issue by MachkrXXIV** [MachkrXXIV/HogSpot#2]
As a user, I want to be able to login / signup depending on if I have an account or not, so that we can store user data that will be relevant to fetch.

Dev note: this story just focuses on the looks and not much logic. Will be separate story.

Start at landing page:
- Big logo of our app
- Button to login
- Button to create new account

For the login page we would just want:
- Username
- Password
- Login button
- Create account text that transitions to sign up activity

The Sign up page would have:
- Enter Username
- Enter Password
- Confirm Password?
- Already have an account text that transitions to login activity

**Comment by Lizzieh17** [comment]
Test
